### ISSUE TITLE
lt_id_ma_q . -- IMR default to NA

### ISSUE THREAD

**Issue by ikashnitsky** [timriffe/DemoTools#101]
IMR parameter (not documented properly) is not supposed to be always required but if not specified gives an error
```
Error in lt_id_ma_q(nMx = mx, nax = ax, AgeInt = age_int) : 
  argument "IMR" is missing, with no default
```
So, I guess, either default to NA (cheap and dirty), or re-write. Surely, need better documentation.  The issue is linked to #100

**Comment by timriffe** [comment]
fixed, thanks!
