### ISSUE TITLE
Issue with documentation

### ISSUE THREAD

**Issue by jmaburto** [timriffe/DemoTools#114]
There is a problem with the documentation in the lt_id_qm_a() when i build the references. Please check

![image](https://user-images.githubusercontent.com/14178224/72728557-f1b7bf00-3b8d-11ea-8dc7-fb588b4811af.png)

**Comment by timriffe** [comment]
I added `#' @title` to that function and the others in that file, regenerated docs and site, and it was fixed. Don't know if that's why it was fixed, or whether it was just due to running again fresh, or my system. Anyway, problem gone now, so I'm closing.
