### ISSUE TITLE
Graduating

### ISSUE THREAD

**Issue by IvanWilli** [timriffe/DemoTools#118]
Hi, 
Thanks for this package, it helps me a lot to spend more time thinking in the problem and how to solve it rather than spend time coding applications.
I tried to graduate with Beers methods and I have some differences in some ages, mostly in group 15-24. Here the example: 

# packs
library(tidyverse)
library(DemoTools)

# data
pop = data.frame(
  age = seq(0,80,5),
  pop = 
    c(1744586,
      1778791,
      1747292,
      1647095,
      1657711,
      1395785,
      1200340,
      1120707,
      1070825,
      1005108,
      915933,
      755022,
      621925,
      517035,
      427206,
      290040,
      245897))

## applying methods
pop_graduate <-
  with(pop, 
     rbind(
       data.frame(Method="Beers"  , age = 0:80, pop = graduate_beers(Value = pop, Age = age, OAG = T)),
       data.frame(Method="Sprague", age = 0:80, pop = graduate_sprague(Value = pop, Age = age, OAG = T)),
       data.frame(Method="Mono"   , age = 0:80, pop = graduate_mono(Value = pop, Age = age, OAG = T)),
       data.frame(Method="pclm"   , age = 0:80, pop = graduate_pclm(Value = pop, Age = age)),
       data.frame(Method="Grabill", age = 0:80, pop = graduate_grabill(Value = pop, Age = age, OAG = T))))

# group to compare
pop_graduate_gr <- pop_graduate %>% 
                mutate(age = rep(0:80, 5), age_gr = trunc(age/5)*5) %>% 
                group_by(Method, age_gr) %>% summarise(pop = sum(pop))
# graph
ggplot() + 
geom_step(data = pop_graduate_gr, aes(age_gr,pop,col=Method))+
geom_step(data = pop, aes(age,pop))

I see differences in Beers and Grabill methods, especially in 15-24. Am I doing something wrong? 
Best
Iván

**Comment by timriffe** [comment]
Thanks @IvanWilli and very sorry for the late reply. No you're not doing anything wrong. Beers and Grabill methods aren't constrained. They're more like graduation + light smoothing. This is a nice demonstration of that. We'll try to make that clearer in the vignette.
