### ISSUE TITLE
Bachi formulas need fixing 

### ISSUE THREAD

**Issue by peterdavjohnson** [timriffe/DemoTools#125]
The current formulas used for the Bachi index are not correct (except when pasex=TRUE).  The revised formulas (sent separately) combined with consistent specification of ageMin and ageMax would remove the need for the pasex variable and make the results consistent with PASEX with ageMin=23 and ageMax=77.

**Comment by timriffe** [comment]
- [ ] generalize age bounds of `pasex` if statement
- [ ] re-write default calculations to PJ's version

**Comment by timriffe** [comment]
fixed in branch `heapingfixes`
