### ISSUE TITLE
check_heaping_myers: AgeMax calc and use inconsistent with input ageMax

### ISSUE THREAD

**Issue by peterdavjohnson** [timriffe/DemoTools#137]
The value of AgeMax calculated within the function is inconsistent with the concept of the input ageMax being inclusive.  The calculations are correct, but if the function is changed to return more info, it would be good to include the AgeMax used and have it be consistent with the ageMax input (e.g., if you request ages 10-89 then the return should indicate it used those ages, but if you requested 10-90 it should indicate that 10-89 was actually used.

```
Diff    <- ageMax - ageMin + 1
  AgeMax <- ageMin + trunc(Diff/10)*10 -1
  
  # may as well be certain here. NOTE THIS SHOULD BE MOVED UP
  stopifnot(ageMax <= max(Age))
  
  ind     <- Age >= ageMin & Age <= AgeMax
```

**Comment by timriffe** [comment]
this should be fixed now in the `heapingfixes` branch
