### ISSUE TITLE
bare-bones cohort interpolation

### ISSUE THREAD

**Issue by timriffe** [timriffe/DemoTools#147]
Write a new version of `interp()` that interpolates within cohorts between adjacent censuses. Age-period interpolation can fill in the infant triangle, and the old-age empty triangle can be filled in some cheap way. For this, we will assume that population is uniformly distributed within age groups, see helper function `ypart()`.

**Comment by cimentadaj** [comment]
`ypart` is now defunct. `dec.date` does everything, by the way.
