### ISSUE TITLE
dependency on 'fertestr'

### ISSUE THREAD

**Issue by markalava** [timriffe/DemoTools#149]
`install_github("timriffe/DemoTools")` complains that package `fertestr` is not available. Found it at `https://github.com/josehcms/fertestr` but is it possible to get `install_github` to take care of it (or mention in the readme)? 
thx!
Mark

**Comment by timriffe** [comment]
Thanks for noting. I've added a line to the `DESCRIPTION` now that should handle this dependency. Will close this issue when I get a confirmation it's working
