### ISSUE TITLE
IRD needs to unlist inputs before using is.infinite()

### ISSUE THREAD

**Issue by peterdavjohnson** [timriffe/DemoTools#150]
Sending a part of a data.frame to IRD gives an error message.  This would seem to be fixed if the following change is made:
`ratio[is.infinite(unlist(ratio))] <- NA`

**Comment by timriffe** [comment]
Thanks Peter, can you paste an example of what you're talking about so I can understand better the issue?

**Comment by peterdavjohnson** [comment]
Hi Tim,

Attached is my code (with the IRD code corrected) and the input file it
uses.

pj

**Comment by timriffe** [comment]
OK, looked at it, the arguments should be vectors, per the documentation, not single-column `data.frames`. It's cheap to make it robust to this, though.One could add this in the header:

```
  pop1 <- unlist(pop1)
  pop2 <- unlist(pop2)
```

It could also be handled more completely. Another option, more consistent with the rest of the package, would be to do add a break:

```
stopifnot(is.vector(pop1) & is.vector(pop2)
```
This is my preference, and it'll also give a clearer warning message. I've pushed this to the `coh` branch, which will soon merge over to master. Most `DemoTools` functions take vectors as arguments. This situation could be remedied in your loop just as well to make the arguments conform with expectations.

Thanks for pointing this out
