### ISSUE TITLE
use {countrycode} matching whenever country name is used to filter data

### ISSUE THREAD

**Issue by ikashnitsky** [timriffe/DemoTools#166]
We need to systematically offer the users easy matching the data irrespective of the exact wording of the country string, i.e. "Russian Federation", "Russia", "RUS", or "RU" should all work

**Comment by cimentadaj** [comment]
@timriffe was a bit skeptical of adding more dependencies unless they are critical for the functioning of DemoTools (specially after having to revive a dependency that broke himself). Do you think this is critical for DemoTools usage?

**Comment by timriffe** [comment]
`countrycode` is light weight, so it's not a big issue to add it as dependency. This only if the UN country codes we might plausibly want to use are in there. @cimentadaj has a better sense of these from `DDSQLtools` I think. For births or SRB, the file `DemoToolsData::WPP2019_births` includes columns  `LocID` `ISO3`  `ISO2`  `LocName`. For lifetables we've used `fertestr::fetchLifeTableWP2019()`, which calls `fertestr::get_location_code()`. I have the impression it needs location names, but then converts these to codes. Perhaps not as flexible as what you're imagining. So if you had a resolver, it would need to produce a correct location name for `fertestr::fetchLifeTableWP2019()` at least. I think this is nice but it can also wait until other red lights stop blinking.

**Comment by timriffe** [comment]
now `country` is being changed to `location` everywhere, and it can be either a spelled-out country name (tricky for some countries), or else a UNPD `LocID`. We can add ISO3 support in the future using a lookup table in `DemoToolsData`
