### ISSUE TITLE
New depency on development `rstan`

### ISSUE THREAD

**Issue by cimentadaj** [timriffe/DemoTools#176]
Rstan is causing many problems here and there. See for example #136 but also some local problems when running migration problems. I managed to fix the local problems by pumping `rstan` to their latest development version `2.26.0`. Users should be encouraged to install this versions using this:

```r
install.packages("rstan", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
```

Maybe with this we can already begin to fix #136.

**Comment by timriffe** [comment]
Thx @cimentadaj Can this be handled with the `Remotes:` field in
`DESCRIPTION`? or do users really need to do this?

**Comment by cimentadaj** [comment]
I don't think so. `2.26.0` is actually a branch that they will soon merge
to GH.

Best,

-----------------------------------


Jorge Cimentada
*https://cimentadaj.github.io/ <https://cimentadaj.github.io/>*
