### ISSUE TITLE
"..." argument 

### ISSUE THREAD

**Issue by mpascariu** [timriffe/DemoTools#19]
It think it would be nice to have the `…` argument in all external functions from `DemoTools`. It would make my life a lot easier when calling functions in `DDSQLtools` (coding wise). Also, this would allow the user to play with the function specific arguments directly from wrap function. For now I need the dots in `beers`, `grabill` and `sprague`.

Is this acceptable?
Marius

**Comment by timriffe** [comment]
no need to add ... explicitly to functions being called.
