### ISSUE TITLE
LC w limited data - tests

### ISSUE THREAD

**Issue by IvanWilli** [timriffe/DemoTools#190]
TODO: 
- [x] document auxiliary functions add @export
- [x] test against the spreadsheet output (assuming necessary pre-processing is done).
- [x] test exact_error(). For example min time points required by theory (3).
 - [x] test success for different combinations of inputs: single/abdiged/mixed ages, passing all extraArgs from lt_abr.
 - [x] test warnings if verbose = TRUE.
 - [x] fix Single closeout confussion in default args
 - [x] make single-sex version; interp_lc_lim will be wrapper, flexible w optional crossover constraint.

Pend:
- Not confortable yet with scoping of extra args in the direction: `interp_lc_lim()` -> `lt_ambiguous()` -> `lt_abridged()`

**Comment by IvanWilli** [comment]
Example where closeout not working @timriffe, with `load_all `in lee-carter branch.
```
m = c(0.0193406941932237, 0.000984035295657068, 0.000321460554112355, 
    0.000328877174136356, 0.000524936251632606, 0.000659693754873828, 
    0.000852297051544039, 0.00113694415219134, 0.00154462862224308, 
    0.00221467364802835, 0.00312669692168282, 0.00457764893363684, 
    0.00650050245059612, 0.00994264071753672, 0.014401504100205, 
    0.0216120888775089, 0.0321550520984863, 0.0459524452296568, 0.0670373903849238, 
    0.101911165266297, 0.161445531913397, 0.266518374610508)
Age = c(0,1,seq(5,100,5))
m_hat = lt_abridged(nMx = m, 
            Age = Age,
            Sex = "f", 
            OAnew = 130,
            extrapLaw = "kannisto", 
            extrapFrom = 100, 
            extrapFit = seq(60,95,5)
            )
plot(c(Age,seq(105,130,5)),
     m_hat$nMx,
     log="y",t="o")
points(Age,m,col=2)
```
If I set to `extrapFit = seq(60,100,5)` works.

**Comment by timriffe** [comment]
extrapolation behavior fixed by changing default `opt.method` of `lt_rule_m_extrapolate()` from `"poissonL"` to `"LF2"`. Namely, offsets aren't massed in, so Poisson fit makes less sense when there are few data points

**Comment by IvanWilli** [comment]
@timriffe all done. Close or keep this issue for future imrpovements?
