### ISSUE TITLE
OPAG unit tests

### ISSUE THREAD

**Issue by timriffe** [timriffe/DemoTools#192]
- [x] check for success in a few different input scenarios
- [x] check sums match between input and output
- [x] check output of proper length
- [x] check for console output when informative warnings should be generated
- [x] expect error if `OAnew > max(Age_nLx)`
- [x] expect errors in other reasonable situations
- [x] canonical test: if the census is actually a stationary population, identical to nLx itself, then we hope to return something proportional to it.
- [x] canonical test: if input census is an exact stable pop (use auxiliary function `OPAG_nLx_warp_r`)

**Comment by tbernardesfaria** [comment]
Hi Tim, maybe you can assign this issue for me.
