### ISSUE TITLE
Error message with basepop_five()

### ISSUE THREAD

**Issue by sarahertog** [timriffe/DemoTools#197]
Hi Tim,
I am getting the following error message after calling basepop_five():

Error: 'WPP2019_births' is not an exported object from 'namespace:DemoToolsData'

**Comment by timriffe** [comment]
Is this using version 01.13.05?

**Comment by sarahertog** [comment]
Yes.  I just loaded the latest DemoTools this morning.

**Comment by timriffe** [comment]
Does the following work for you?:

`WPP2019_births <- DemoToolsData::WPP2019_births`

**Comment by sarahertog** [comment]
No: 

> WPP2019_births <- DemoToolsData::WPP2019_births
Error: 'WPP2019_births' is not an exported object from 'namespace:DemoToolsData'

**Comment by timriffe** [comment]
Try this:
`remotes::install_github("timriffe/DemoToolsData",force=TRUE)`

**Comment by sarahertog** [comment]
Success. Thank you!!

**Comment by peterdavjohnson** [comment]
Hi Tim and Sara,

I am getting NA's back when I try using RefDate = 1950.  I get the messages:

nLxDate(s) 1949.75329589844, 1942.75329589844 is/are below 1955. Capping at
1955
nLxDate(s) 1949.75329589844, 1942.75329589844 is/are below 1955. Capping at
1955
AsfrDate(s) 1949.75329589844, 1942.75329589844 is/are below 1955. Capping
at 1955
nLxDate(s) 1949.75329589844, 1942.75329589844 is/are below 1955. Capping at
1955
nLxDate(s) 1949.75329589844, 1942.75329589844 is/are below 1955. Capping at
1955
AsfrDate(s) 1949.75329589844, 1942.75329589844 is/are below 1955. Capping
at 1955

Is that correct? I thought it would just use data from 1955.

Thanks,
pj

**Comment by timriffe** [comment]
I tested using the example from `basepop_five()`, but adjusted like this:

```
refDate <- 1986
country <- "Brazil"
pop_female_single <- fertestr::FetchPopWpp2019(country,
                                               refDate,
                                               ages = 0:100,
                                               sex = "female")
pop_female_counts <- single2abridged(setNames(pop_female_single$pop,
                                              pop_female_single$ages))
pop_male_single   <- fertestr::FetchPopWpp2019(country,
                                               refDate,
                                               ages = 0:100,
                                               sex = "male")
pop_male_counts   <- single2abridged(setNames(pop_male_single$pop,
                                              pop_male_single$ages))
Age <- names2age(pop_male_counts)
# Automatically downloads the nLx, ASFR, and SRB data
bpe <- basepop_five(
  country = country,
  refDate = 1950,
  Females_five = pop_female_counts,
  Males_five = pop_male_counts,
  Age = Age,
  SRB=1.05
)
```

There we just pretend that the population inputs actually have a 1950 reference date in order to force download of earlier dates. This produces valid output. What country are you trying with?

**Comment by peterdavjohnson** [comment]
Hi Tim,

I get the error for Guam 1950.  I am on Google Hangouts if you want to
discuss further.

pj
