### ISSUE TITLE
check_heaping_bachi allows ageMax higher than last age

### ISSUE THREAD

**Issue by peterdavjohnson** [timriffe/DemoTools#201]
I just discovered that check_heaping_bachi allows ageMax to be higher than the available ages.  The 1951 India census was smoothed and has an open-ended age group of 70+, but if no ageMax is given it uses the default of 77 and results in an index of 4.15 with the percent digit 0 = 14.13.  With ageMax=67 the index is 0.10 and percent digit 0 = 10.02. I can just fix the ageMax myself for now (as shown below), but this needs to be fixed at some point.

```
library(DemoTools)
library(dplyr)

MyDir <- "~/PETER/UNPOP/POPULATION/DDHsmthPES/DiffNCE"

ageMin <- 23

IndiaPop1 <- read.csv(paste0(MyDir, "/IndiaPop1.txt"))

Pop1951m <- filter(IndiaPop1, CenYr==1951, Sex=="Male")$PopObs

OpenAge <- max(filter(IndiaPop1, CenYr==1951, Sex=="Male")$Age)

BachiDetail <- check_heaping_bachi(Pop1951m, Age = 0:OpenAge, 
                                       details = TRUE)
print(paste("Index=",BachiDetail$index, 
            "pct0=",BachiDetail$pct[1],
            "ageMin=",BachiDetail$ageMin,
            "ageMax=",BachiDetail$ageMax
            ))

MaxDecades <- floor((OpenAge - 1 - 23 - 4 )/10)
ageMax <- ageMin + 4 + 10 *floor((OpenAge - 28)/10)

BachiDetail2 <- check_heaping_bachi(Pop1951m, Age = 0:OpenAge, 
                                        ageMin = ageMin,
                                       ageMax = ageMax, 
                                       details = TRUE)

print(paste("Index=",BachiDetail2$index, 
            "pct0=",BachiDetail2$pct[1],
            "ageMin=",BachiDetail2$ageMin,
            "ageMax=",BachiDetail2$ageMax
))

```

[IndiaPop1.txt](https://github.com/timriffe/DemoTools/files/5957827/IndiaPop1.txt)

**Comment by timriffe** [comment]
The new behavior is to lower `ageMax` in steps of 10 years until it is lower than `max(Age)`. A message is printed to the console if this happens, thanks for reporting
