### ISSUE TITLE
rgl error on windows install

### ISSUE THREAD

**Issue by timriffe** [timriffe/DemoTools#203]
@cimentadaj this was previously OK, any ideas?
![image](https://user-images.githubusercontent.com/904603/107940280-4774bb80-6f88-11eb-8fc3-fed11bdceb24.png)

**Comment by cimentadaj** [comment]
I think this should be fixed in https://github.com/timriffe/DemoTools/pull/206 now.

**Comment by cimentadaj** [comment]
Yep, I think this can be closed now.
