### ISSUE TITLE
extraMortality() error

### ISSUE THREAD

**Issue by timriffe** [timriffe/DemoTools#59]
the following build: [fails](https://ci.appveyor.com/project/timriffe/demotools/builds/20153012)

It's due to a `MortalityLaws` law not being available. Can you take a look @mpascariu ?

**Comment by mpascariu** [comment]
yes, I am aware of this. One of the laws was renamed in the MortalityLaws v1.7.0, on CRAN now. I will update here too.

**Comment by mpascariu** [comment]
The solution was provided here #60.
