### ISSUE TITLE
recheck maxAge arg

### ISSUE THREAD

**Issue by timriffe** [timriffe/DemoTools#70]
help file says lower bound of upper age group, but examples show otherwise. for example 89 vs 90. Decide and make consistent...

**Comment by jmaburto** [comment]
I double checked the argument ageMax or maxAge. In the details we say it is inclusive. In the examples, if it says 89 is intended to include up to 89, or if it says 90 then include 90. In some cases it says 90 to duplicate the results with the spreadsheets (e.g. Myers) and others depend on what the original paper suggests but all of them are inclusive. I would see an inconsistency in 5-year age groups, so 70 to include 70-74 and not 75.  Or what do you mean by consistent?

**Comment by timriffe** [comment]
I was using `Myers()` yesterday and in examples used `maxAge = 90` but I was expecting to see 89 per the documentation. Doesn't mean 90 was wrong. Thanks for double checking. I think your 5-year age group observation is a valid point. Thinking ceiling interpretation is more intuitive. Won't ask you to change it tho, as it'd require changing function guts too. Will sit on it a while
