### ISSUE TITLE
Check is_single after subsetting to relevant ages

### ISSUE THREAD

**Issue by gergness** [timriffe/DemoTools#81]
Thanks so much for this work! Hit a minor annoyance today - I wish the age quality measures would subset to the relevant ages before checking `is_single()`. Sometimes I have data where there are age categories, but they are beyond the age groups relevant to the measure.

``` r
library(DemoTools)
df <- data.frame(
  age = c(0:90, 100),
  count = 10
)

Whipple(df$count, df$age, ageMin = 25, ageMax = 65)
#> Error in Whipple(df$count, df$age, ageMin = 25, ageMax = 65): is_single(Age) is not TRUE


# Problem is that is_single fails because of 100 age group
# but this shouldn't matter because ageMax is 65
subset_df <- subset(df, age >= 25 & age <= 65)
Whipple(subset_df$count, subset_df$age, ageMin = 25, ageMax = 65)
#> [1] 1
```

<sup>Created on 2019-04-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by timriffe** [comment]
Thanks for pointing this out, good suggestion, will do this, but can't
guarantee by when.

**Comment by timriffe** [comment]
This has been implemented, thanks again!

```
df <- data.frame(
		age = c(0:90, 100),
		count = 10
)

Whipple(df$count, df$age, ageMin = 25, ageMax = 65)
#[1] 1
Whipple(df$count, df$age, ageMin = 25, ageMax = 100)
#Error in Whipple(df$count, df$age, ageMin = 25, ageMax = 100) : 
```

**Comment by gergness** [comment]
Many thanks for the quick update!
