### ISSUE TITLE
LTabr() closeout returning NA or NaN

### ISSUE THREAD

**Issue by patrick-gerland** [timriffe/DemoTools#82]
When extrapolating using the example data on a restricted young age range, we can induce `NAs`, probably not a desirable result. Maybe a bug?

```
Exposures <- c(100958,466275,624134,559559,446736,370653,301862,249409,247473,223014,172260,149338,127242,105715,79614,53660,
		31021,16805,8000,4000,2000,1000)

Deaths <- c(8674,1592,618,411,755,1098,1100,1357,1335,3257,2200,4023,2167,4578,2956,4212,2887,2351,1500,900,500,300)

Age    <- c(0, 1, seq(5, 100, by = 5))
AgeInt <- c(diff(Age), NA)

PASLT <- LTabr(
    Deaths = Deaths, 
		Exposures = Exposures, 
		Age = Age,
		AgeInt = AgeInt,
		axmethod = "pas",
		IMR = .1,
		region = "n",
		Sex = "m")
```

**Comment by timriffe** [comment]
Running this example, the only `NA` produced is for the final value of `AgeInt`, which for this variable stands for the open age group in this package (`Inf` would have been another possible choice, but we went with `NA`. I'm not a fan of `-1` for this case). Was there a different argument setting that produced `NA`s in the actual lifetable columns?
